name: flutter_weather_app
description: Une application météo avec architecture propre
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.3.2

  # State Management
  flutter_bloc: ^9.1.1

  # Dependency Injection
  get_it: ^7.6.4

  # Localization & Date Formatting
  intl: ^0.19.0

  # Icons
  font_awesome_flutter: ^10.5.0

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Equatable pour comparer les objets
  equatable: ^2.0.5
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.1
  freezed: ^2.4.1


flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700